In [1]:
import pandas as pd

In [2]:
df = pd.read_csv (r'D:\adrope\Datos\casen\Casen 2017.csv', sep=';')
df.head()

D:\adrope\Programa\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (44,765,766,767,768,769,770,771,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,folio,o,id_vivienda,hogar,region,provincia,comuna,zona,expr,expc,...,hh_d_estado,hh_d_servbas,hh_d_entorno,hh_d_accesi,hh_d_medio,hh_d_appart,hh_d_tsocial,hh_d_seg,pobreza_multi_4d,pobreza_multi_5d
0,110110020201,1,1101100202,1,1,11,1101,1,39,33,...,0,1,1,0,1,0,0,1,,
1,110110020301,1,1101100203,1,1,11,1101,1,39,33,...,1,0,0,0,0,0,0,0,1,1
2,110110020401,1,1101100204,1,1,11,1101,1,39,33,...,1,0,1,0,1,0,1,1,,
3,110110020401,2,1101100204,1,1,11,1101,1,39,33,...,1,0,1,0,1,0,1,1,,
4,110110020501,1,1101100205,1,1,11,1101,1,39,33,...,1,1,1,0,1,,1,0,0,

In [3]:
is_131 =  df['provincia']==131
df_stgo = df[is_131]
print(df_stgo.shape)

(31868, 804)

In [4]:
stgo_vivienda = df_stgo[['id_vivienda','region','provincia','comuna','expc','v1','v2','v3','v6','v7','hacinamiento','pobreza']]

In [5]:
stgo_vivienda.head

<bound method NDFrame.head of         id_vivienda  region  provincia  comuna  expc  v1  v2  v3  v6  v7  \
155775  13101100105      13        131   13101    17   4   1   1   2   1
155776  13101100105      13        131   13101    17   4   1   1   2   1
155777  13101100105      13        131   13101    17   4   1   1   2   1
155778  13101100107      13        131   13101    17   4   1   1   2   1
155779  13101100107      13        131   13101    17   4   1   1   2   1
...             ...     ...        ...     ...   ...  ..  ..  ..  ..  ..
187638  13132112902      13        131   13132   107   1   1   1   1   1
187639  13132113014      13        131   13132    70   5   2   1   2   1
187640  13132113014      13        131   13132    70   5   2   1   2   1
187641  13132113014      13        131   13132    70   5   2   1   2   1
187642  13132113014      13        131   13132    70   5   2   1   2   1

        hacinamiento pobreza
155775             1       3
155776             1       3
155777             1       3
155778             1       3
155779             1       3
...              ...     ...
187638             1       3
187639             1       3
187640             1       3
187641             1       3
187642             1       3

[31868 rows x 12 columns]>

In [6]:
stgo_vivienda.to_csv('CASEN_VIVIENDA_STGO.csv')